# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]
excludes = []

[formatter.prettier]
command = "prettier"
options = ["-w"]
excludes = []
includes = ["**/*.{ts,js,yaml,yml,d.ts}"]
